name: Oxlint

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  oxlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sentisis-challenge
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@latest --deny-warnings
